name: autocart-daily

on:
  schedule:
    - cron: "0 16 * * *" # JST 01:00
  workflow_dispatch: {}

jobs:
  run-autocart:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Prepare credentials and run (dry)
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          set -euo pipefail
          if [ -z "${FIREBASE_SERVICE_ACCOUNT:-}" ]; then
            echo "::error::FIREBASE_SERVICE_ACCOUNT is not set. Add it at Settings → Secrets and variables → Actions"
            exit 1
          fi

          mkdir -p .firebase
          printf "%s" "$FIREBASE_SERVICE_ACCOUNT" > .firebase/firebase-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/.firebase/firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS set to $GOOGLE_APPLICATION_CREDENTIALS"

          # run as dry-run for safety; remove --dry for production
          npx -y ts-node --transpile-only src/jobs/checkout/autocart-runner.ts --dry --limit 50 --debug --explain 2>&1 | tee autocart-runner.log
          EXIT_CODE=${PIPESTATUS[0]}
          echo "exit code: $EXIT_CODE"
          if [ "$EXIT_CODE" -ne 0 ]; then exit "$EXIT_CODE"; fi

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: autocart-logs
          path: autocart-runner.log

      - name: Cleanup creds
        if: always()
        run: rm -f .firebase/firebase-key.json || true