name: autocart-daily

# 毎日 01:00 JST -> UTC 前日 16:00
on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch: {}

concurrency:
  group: autocart-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run-autocart:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Cache checkout node_modules
        uses: actions/cache@v4
        with:
          path: src/jobs/checkout/node_modules
          key: ${{ runner.os }}-autocart-${{ hashFiles('src/jobs/checkout/package-lock.json', 'src/jobs/checkout/package.json') }}
          restore-keys: |
            ${{ runner.os }}-autocart-

      - name: Install dependencies (autocart)
        run: |
          if [ -f src/jobs/checkout/package.json ]; then
            echo "Installing dependencies for src/jobs/checkout..."
            npm ci --prefix src/jobs/checkout
          else
            echo "No package.json in src/jobs/checkout; falling back to root npm ci"
            npm ci
          fi

      - name: Setup Firebase service account (if provided)
        run: |
          if [ -n "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" ]; then
            mkdir -p "$GITHUB_WORKSPACE/.firebase"
            printf '%s' "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > "$GITHUB_WORKSPACE/.firebase/firebase-key.json"
            echo "WROTE $GITHUB_WORKSPACE/.firebase/firebase-key.json"
          else
            echo "No FIREBASE_SERVICE_ACCOUNT secret provided; skipping"
          fi
        shell: bash

      - name: Check required secrets (strict)
        env:
          CART_API_KEY: ${{ secrets.CART_API_KEY }}
        run: |
          set -euo pipefail
          if [ -z "${CART_API_KEY:-}" ]; then
            echo "ERROR: required secret CART_API_KEY is not set"
            echo "Add it at: Settings → Secrets and variables → Actions"
            exit 2
          fi
          echo "Secrets check OK"

      - name: Run autocart with Firebase creds
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/.firebase/firebase-key.json
          CART_API_KEY: ${{ secrets.CART_API_KEY }}
        run: |
          set -euo pipefail
          mkdir -p logs
          OUT="logs/autocart-$(date -u +%Y%m%dT%H%M%SZ).log"
          echo "Starting autocart, logging to $OUT"
          npm run start --prefix src/jobs/checkout 2>&1 | tee "$OUT"
          EXITCODE=${PIPESTATUS[0]}
          echo "autocart exited with $EXITCODE"
          exit "$EXITCODE"

      - name: Upload logs/artifact
        uses: actions/upload-artifact@v4
        with:
          name: autocart-logs
          path: logs/*.log

      - name: Post-cache cleanup (noop)
        if: always()
        run: echo "job finished"