name: autocart-daily

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *" # 01:00 JST

concurrency:
  group: autocart-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run-autocart:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # NOTE: キャッシュはトラブルの元になりやすいので一時的に無効化する（コメントアウト）。
      # - name: Cache checkout node_modules
      #   uses: actions/cache@v4
      #   with:
      #     path: src/jobs/checkout/node_modules
      #     key: ${{ runner.os }}-autocart-${{ hashFiles('src/jobs/checkout/package-lock.json', 'src/jobs/checkout/package.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-autocart-

      - name: Install dependencies for autocart
        run: |
          if [ -f src/jobs/checkout/package.json ]; then
            npm ci --prefix src/jobs/checkout
          else
            npm ci
          fi

      - name: Setup Firebase service account (if provided)
        run: |
          if [ -n "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" ]; then
            mkdir -p "$GITHUB_WORKSPACE/.firebase"
            printf '%s' "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > "$GITHUB_WORKSPACE/.firebase/firebase-key.json"
            echo "WROTE $GITHUB_WORKSPACE/.firebase/firebase-key.json"
          else
            echo "No FIREBASE_SERVICE_ACCOUNT secret provided; skipping"
          fi
        shell: bash

      - name: Check required secrets (strict)
        env:
          CART_API_KEY: ${{ secrets.CART_API_KEY }}
        run: |
          set -euo pipefail
          if [ -z "${CART_API_KEY:-}" ]; then
            echo "ERROR: required secret CART_API_KEY is not set"
            exit 2
          fi
          echo "Secrets check OK"

      - name: Build TypeScript (explicit) and run
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/.firebase/firebase-key.json
          CART_API_KEY: ${{ secrets.CART_API_KEY }}
        run: |
          set -euo pipefail
          echo "=== Building checkout TypeScript ==="
          # ビルド（失敗時にログを表示して exit 1）
          npm run build --prefix src/jobs/checkout 2>&1 | tee build.log || (cat build.log && exit 1)
          echo "=== Running built JS ==="
          mkdir -p logs
          OUT="logs/autocart-$(date -u +%Y%m%dT%H%M%SZ).log"
          node src/jobs/checkout/dist/autocart.js 2>&1 | tee "$OUT"
          EXIT=${PIPESTATUS[0]}
          echo "autocart exited with $EXIT"
          exit "$EXIT"

      - name: Upload logs/artifact
        uses: actions/upload-artifact@v4
        with:
          name: autocart-logs
          path: logs/*.log

      - name: Post-run
        if: always()
        run: echo "job finished"