name: run-rpa-for-user

on:
  workflow_dispatch:
    inputs:
      uid:
        description: 'user id'
        required: true
      historyDoc:
        description: 'history doc id (e.g. last-checkout)'
        required: true
      cartPath:
        description: 'cart path (optional)'
        required: false

permissions:
  contents: read
  actions: write

jobs:
  run_rpa:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install apt deps & chrome
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget gnupg ca-certificates unzip xvfb
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update -y
          sudo apt-get install -y google-chrome-stable || true

      - name: Install Python deps (scraper/RPA)
        run: |
          python -m pip install --upgrade pip
          if [ -f src/app/api/cart/checkout/requirements.txt ]; then
            pip install -r src/app/api/cart/checkout/requirements.txt
          fi

      - name: Run AEON RPA (adds items to AEON cart)
        id: rpa
        run: |
          python3 src/app/api/cart/checkout/aeon_netsuper_cart.py \
            --use-firebase \
            --fb-cred "$GOOGLE_APPLICATION_CREDENTIALS" \
            --uid "${{ github.event.inputs.uid }}" \
            --cart-path "${{ github.event.inputs.cartPath || format('users/{0}/cart', github.event.inputs.uid) }}" \
            --dedupe \
            --call-postprocess false \
            --postprocess-history-doc "${{ github.event.inputs.historyDoc }}" \
            --headless
      - name: Run postprocess (move cart -> history)
        if: ${{ success() }}
        run: |
          # node setup
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install -g tsx
          npx tsx src/app/api/cart/checkout/route.ts \
            --cred "$GOOGLE_APPLICATION_CREDENTIALS" \
            --uid "${{ github.event.inputs.uid }}" \
            --history-doc "${{ github.event.inputs.historyDoc }}"